# wifipi.ini - configuration file for wifipi.py

[default]
  # The SSID (network name) of the WiFi network you want to monitor
  ssid = MyNetworkName
  # The polling interval (in seconds) to update the LEDs
  poll_interval = 5
  # The brightness of the LEDs (0.0 - 1.0)
  brightness = 0.7
